name: Deploy to atthost server
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: weather-app-vue3

    name: Build And Deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Create ENV
      run: |
        echo "VITE_API_URL=https://weatherapi-com.p.rapidapi.com" >> .env
        echo "VITE_API_HOST=weatherapi-com.p.rapidapi.com" >> .env
        echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env

    - name: Build for production
      run: npm run build

    - name: Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: 6022
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        scp_source: ./dist
        scp_target: ./websites/weather-vue